name: GraalVM build
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Maven package
        run: |
          mvn clean package
          java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image -jar target/jrebel-license-all.jar -s 15
          mvn -Pnative package
      - name: Prepare Release File (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          cp target/jrebel-license ./jrebel-license-Linux-${{ github.ref_name }}
          cp target/jrebel-license-all.jar ./jrebel-license-${{ github.ref_name }}.jar
      - name: Login to Docker Hub
        if: matrix.platform == 'ubuntu-latest'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        if: matrix.platform == 'ubuntu-latest'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: jackkke/jrebel-license:${{ github.ref_name }}
          build-args: |
            VERSION=${{ github.ref_name }}
      - name: Build and push alpine
        if: matrix.platform == 'ubuntu-latest'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-alpine
          push: true
          tags: jackkke/jrebel-license:${{ github.ref_name }}-alpine
          build-args: |
            VERSION=${{ github.ref_name }}
      - name: Prepare Release File (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          cp target/jrebel-license.exe ./jrebel-license-${{ github.ref_name  }}.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            jrebel-license-*
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}